"""
rag.py - RAG (Retrieval Augmented Generation) pipeline module.

Provides three core functions:
  - extract_text_from_pdf : extract raw text from an uploaded PDF
  - create_vector_store   : chunk text, embed with Google AI, store in ChromaDB
  - ask_question          : retrieve relevant chunks and answer with Gemini
"""

import os

from dotenv import load_dotenv
import PyPDF2
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

# Load .env so GOOGLE_API_KEY is available when this module is used
load_dotenv()

# Directory where FAISS will persist its index across restarts
FAISS_PERSIST_DIR = "./faiss_index"


def extract_text_from_pdf(uploaded_file) -> str:
    """
    Extracts and returns all text content from a PDF file.

    Iterates over every page of the PDF and concatenates the text.
    Returns an empty string if extraction fails on any page.

    Args:
        uploaded_file: A Streamlit UploadedFile object (file-like, in bytes mode).

    Returns:
        str: Raw text extracted from all pages of the PDF.

    Raises:
        Exception: Re-raises any unexpected error so the caller can handle it.
    """
    text = ""
    try:
        # PdfReader accepts a file-like object directly
        pdf_reader = PyPDF2.PdfReader(uploaded_file)

        for page_number, page in enumerate(pdf_reader.pages):
            try:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n"
            except Exception as page_error:
                # Skip pages that cannot be parsed but continue with the rest
                print(f"Warning: Could not extract text from page {page_number}: {page_error}")

    except Exception as e:
        raise Exception(f"Failed to read PDF: {e}")

    return text


def create_vector_store(text: str):
    """
    Splits the given text into overlapping chunks, generates OpenAI embeddings
    for each chunk, and persists them in a local ChromaDB vector store.

    Chunking parameters:
        - chunk_size    = 1000 characters
        - chunk_overlap = 200 characters  (preserves context across chunks)

    The ChromaDB collection is stored at CHROMA_PERSIST_DIR (./chroma_db)
    so data survives application restarts.

    Args:
        text (str): Raw text to be indexed.

    Returns:
        Chroma: A LangChain Chroma vectorstore instance ready for retrieval.

    Raises:
        Exception: Re-raises any error encountered during embedding or storage.
    """
    try:
        # ── 1. Split the raw text into manageable, overlapping chunks ────────
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len,
            separators=["\n\n", "\n", " ", ""],  # prefer natural break points
        )
        chunks = text_splitter.split_text(text)

        if not chunks:
            raise ValueError("No text chunks were produced. The PDF may be empty or image-only.")

        # ── 2. Google Gemini embeddings (uses GOOGLE_API_KEY, no PyTorch needed) ─
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key:
            raise ValueError("GOOGLE_API_KEY not found. Please set it in your .env file.")
        embeddings = GoogleGenerativeAIEmbeddings(
            model="gemini-embedding-001",
            google_api_key=api_key,
        )

        # ── 3. Build FAISS vector store and persist to disk ──────────────────
        vectorstore = FAISS.from_texts(texts=chunks, embedding=embeddings)
        os.makedirs(FAISS_PERSIST_DIR, exist_ok=True)
        vectorstore.save_local(FAISS_PERSIST_DIR)

        return vectorstore

    except Exception as e:
        raise Exception(f"Failed to create vector store: {e}")


def ask_question(vectorstore, query: str) -> str:
    """
    Answers a natural-language question using the RAG pattern (LCEL):
      1. Retrieve the k=3 most relevant chunks from the vector store.
      2. Format them as context and pass to Gemini via a prompt chain.
      3. Return the model's answer as a plain string.

    Args:
        vectorstore: A LangChain Chroma vectorstore instance.
        query (str): The user's question in natural language.

    Returns:
        str: The answer generated by Gemini based on the retrieved context.

    Raises:
        Exception: Re-raises any error from retrieval or generation.
    """
    try:
        # ── 1. Configure the retriever to fetch top-5 relevant chunks ────────
        retriever = vectorstore.as_retriever(
            search_type="similarity",
            search_kwargs={"k": 5},
        )

        # ── 2. Initialise Gemini with a low temperature for factual answers ──
        api_key = os.getenv("GOOGLE_API_KEY")
        llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            temperature=0.2,
            google_api_key=api_key,
        )

        # ── 3. Build a detailed prompt grounding the model in the PDF ─────────
        prompt = ChatPromptTemplate.from_template(
            """You are an expert assistant helping users understand the content of a PDF document.

Use ONLY the information from the context below to answer the question.
Do NOT use any outside knowledge. If the answer is not found in the context,
say exactly: "I could not find information about that in the provided document."

When answering:
- Be thorough and specific, referencing details from the document.
- If the question asks for a list or steps, format your answer with bullet points or numbered steps.
- If the question is about a number, date, or name, quote it precisely from the document.
- Keep your answer focused and avoid repeating the same information.

Context from the PDF:
{context}

Question: {question}

Detailed Answer:"""
        )

        # ── 4. Helper to concatenate retrieved Document objects into one string
        def format_docs(docs):
            return "\n\n".join(doc.page_content for doc in docs)

        # ── 5. Build the LCEL chain: retrieve → prompt → LLM → parse ─────────
        chain = (
            {"context": retriever | format_docs, "question": RunnablePassthrough()}
            | prompt
            | llm
            | StrOutputParser()
        )

        answer = chain.invoke(query)
        return answer

    except Exception as e:
        raise Exception(f"Failed to generate answer: {e}")
